# Generated by Django 4.0.4 on 2022-04-18 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lastname',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='some info about project', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='period',
            field=models.IntegerField(default=0, verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Project Default', max_length=30, verbose_name='Project Name'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.IntegerField(default=0, verbose_name='Total Budget'),
        ),
        migrations.CreateModel(
            name='yearBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000, verbose_name='Year')),
                ('budget', models.IntegerField(default=0, verbose_name='Year Budget')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceProject.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2000, 1, 1))),
                ('cost', models.IntegerField(default=0)),
                ('operation', models.CharField(default='No Name', max_length=50)),
                ('more_info', models.TextField(default='some info about operation', verbose_name='More Informations')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceProject.project', verbose_name='Project')),
            ],
        ),
    ]
