# Generated by Django 4.0.4 on 2022-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinanceProject', '0002_remove_project_firstname_remove_project_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='operation',
            field=models.CharField(default='Operation Name', max_length=50),
        ),
    ]
